version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.16
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  app:
    container_name: app
    image: python:3.9.16-alpine3.17
    restart: always
    working_dir: /app
    volumes:
      - $PWD:/app
    environment:
      - PORT=5050
      - MONGO_URI=mongodb://mongodb:27017/my_db?retryWrites=true&w=majority
    ports:
      - 5050:5050
    depends_on:
      - mongodb
    command: sh -c "pip install -r requirements.txt && sleep 4 && python app.py"